### ISSUE TITLE
Favicon 404 request on each page transition

### ISSUE THREAD

**Issue by samajammin** [cwaring/vuepress-plugin-ipfs#1]
Hey @cwaring - thanks for this awesome plugin! 

ethereum.org is up & running on IPFS (https://github.com/ethereum/ethereum-org-website/pull/896)!

One (minor) issue I'm noticing is with the favicon. It seems to work _sometimes_ but others I'm seeing failed requests on every page I navigate to (I'm guessing because it's trying to access the favicon via a relative link from each page):
![Image 2020-03-27 at 9 35 45 AM](https://user-images.githubusercontent.com/8097623/77778627-87e4e700-700e-11ea-86ff-554cf0b603e4.png)

Any idea how to solve this favicon issue? I tried using/importing `$withBase` in the config.js but I suspect that's not doable.

Cheers

**Comment by cwaring** [comment]
👋

I've been looking into this as a future enhancement because it's related to how VuePress renders the templates client-side. Essentially once the application mounts on the body of the HTML the header elements stay the same, which is why you hit a 404 when routing between different depths because it doesn't replace the header paths.

If you hard refresh any root you'll notice that the initial served html has the correct favicon path, so this won't actually be a 404 error for crawling via search engines.

A simple way to get rid of the client-side 404 for now is to use an absolute url for the favicon, however this means that the site package will have an external dependancy and not be fully distributed. So that's a trade-off to consider.

When I've had chance to experiment further I'll update this issue but I wouldn't consider it breaking for now. If you discover a solution in the meantime let me know.
