### ISSUE TITLE
When is $withBase necessary?

### ISSUE THREAD

**Issue by samajammin** [cwaring/vuepress-plugin-ipfs#2]
Hello again 😄 

I'm curious when the `$withBase` helper is needed.

We just added IPFS support with this plugin (https://github.com/ethereum/ethereum-org-website/pull/896) & everything seems to be working. I'm actually surprised [our assets page](https://gateway.pinata.cloud/ipfs/QmVmmSbZVmcWBaDGu93nB2dDPHCCxLmJG1tjeDvrdLggmo/assets/#general-assets) is serving images correctly because we didn't add the helper within [that component ](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/.vuepress/components/AssetItem.vue) but it was needed for our other components (e.g. [this one](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/.vuepress/components/BuildPage.vue)).

Are there specific rules for when this helper is needed? I thought it was within any component that references an image within the /public/ directory.

Thanks in advance!

**Comment by cwaring** [comment]
Yes you're right, it should be used for any assets in the public folder referenced via a string path. The reason that assets page works is because you are running them through `require()` therefore webpack is managing the inclusion by hashing and bundling them in the final distribution.

If you are doing this I'd actually recommend moving the assets outside of the public folder because otherwise you will be uploading two copies of the files in the final build.

Also worth noting that you have to be careful with dynamic asset requires because webpack will include all assets in the referenced folder, which could cause unnecessary bloat.
